In [120]:
from keras.utils import pad_sequences
from pickle import dump,load
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
import numpy as np

In [87]:
def readNames(fileName):
    return open(fileName,'r',encoding='utf8').readlines()

In [88]:
dataNames = readNames('male.txt')

In [89]:
def generateSequence():
    results = []
    for name in dataNames:
        for index in range(2,len(name)):
            results.append(name[:index+1])
    return np.array(results)

In [90]:
dataNames = generateSequence()

In [91]:
dataNames[:10]

array(['Aam', 'Aami', 'Aamir', 'Aamir\n', 'Aar', 'Aaro', 'Aaron',
       'Aaron\n', 'Abb', 'Abbe'], dtype='<U16')

In [92]:
dataNames = [[char for char in name] for name in dataNames]

In [93]:
dataNames

[['A', 'a', 'm'],
 ['A', 'a', 'm', 'i'],
 ['A', 'a', 'm', 'i', 'r'],
 ['A', 'a', 'm', 'i', 'r', '\n'],
 ['A', 'a', 'r'],
 ['A', 'a', 'r', 'o'],
 ['A', 'a', 'r', 'o', 'n'],
 ['A', 'a', 'r', 'o', 'n', '\n'],
 ['A', 'b', 'b'],
 ['A', 'b', 'b', 'e'],
 ['A', 'b', 'b', 'e', 'y'],
 ['A', 'b', 'b', 'e', 'y', '\n'],
 ['A', 'b', 'b'],
 ['A', 'b', 'b', 'i'],
 ['A', 'b', 'b', 'i', 'e'],
 ['A', 'b', 'b', 'i', 'e', '\n'],
 ['A', 'b', 'b'],
 ['A', 'b', 'b', 'o'],
 ['A', 'b', 'b', 'o', 't'],
 ['A', 'b', 'b', 'o', 't', '\n'],
 ['A', 'b', 'b'],
 ['A', 'b', 'b', 'o'],
 ['A', 'b', 'b', 'o', 't'],
 ['A', 'b', 'b', 'o', 't', 't'],
 ['A', 'b', 'b', 'o', 't', 't', '\n'],
 ['A', 'b', 'b'],
 ['A', 'b', 'b', 'y'],
 ['A', 'b', 'b', 'y', '\n'],
 ['A', 'b', 'd'],
 ['A', 'b', 'd', 'e'],
 ['A', 'b', 'd', 'e', 'l'],
 ['A', 'b', 'd', 'e', 'l', '\n'],
 ['A', 'b', 'd'],
 ['A', 'b', 'd', 'u'],
 ['A', 'b', 'd', 'u', 'l'],
 ['A', 'b', 'd', 'u', 'l', '\n'],
 ['A', 'b', 'd'],
 ['A', 'b', 'd', 'u'],
 ['A', 'b', 'd', 'u', 'l'],

In [94]:
tokenizer = Tokenizer(lower=False)
tokenizer.fit_on_texts(dataNames)

In [95]:
sequences = tokenizer.texts_to_sequences(dataNames)

In [96]:
sequences = pad_sequences(sequences,padding='pre')

In [97]:
sequences

array([[ 0,  0,  0, ..., 18,  2, 14],
       [ 0,  0,  0, ...,  2, 14,  4],
       [ 0,  0,  0, ..., 14,  4,  3],
       ...,
       [ 0,  0,  0, ...,  6,  3,  3],
       [ 0,  0,  0, ...,  3,  3,  6],
       [ 0,  0,  0, ...,  3,  6,  8]])

In [98]:
xFeatures = sequences[:,:-1]
yLabels = sequences[:,-1]

In [99]:
xFeatures

array([[ 0,  0,  0, ...,  0, 18,  2],
       [ 0,  0,  0, ..., 18,  2, 14],
       [ 0,  0,  0, ...,  2, 14,  4],
       ...,
       [ 0,  0,  0, ..., 46,  6,  3],
       [ 0,  0,  0, ...,  6,  3,  3],
       [ 0,  0,  0, ...,  3,  3,  6]])

In [100]:
yLabels

array([14,  4,  3, ...,  3,  6,  8])

In [106]:
yLabelsBinary

array([[ True, False, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       [False, False,  True, ...,  True, False, False],
       ...,
       [False, False,  True, ...,  True, False, False],
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False,  True]])

In [118]:
xFeatures.shape,yLabelsBinary.shape

((14407, 15), (14407, 14407))

In [124]:
vocabSize = len(tokenizer.word_index) + 1
seqLength = xFeatures.shape[1]
seqLength,vocabSize

(15, 55)

In [125]:
yLabelsBinary = to_categorical(yLabels,num_classes=vocabSize)

In [142]:
yLabelsBinary[0],yLabels[0],tokenizer.word_index

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.], dtype=float32),
 14,
 {'e': 1,
  'a': 2,
  'r': 3,
  'i': 4,
  'n': 5,
  'o': 6,
  'l': 7,
  '\n': 8,
  't': 9,
  'd': 10,
  'h': 11,
  's': 12,
  'u': 13,
  'm': 14,
  'c': 15,
  'y': 16,
  'S': 17,
  'A': 18,
  'M': 19,
  'b': 20,
  'R': 21,
  'T': 22,
  'C': 23,
  'g': 24,
  'B': 25,
  'H': 26,
  'G': 27,
  'W': 28,
  'D': 29,
  'J': 30,
  'f': 31,
  'v': 32,
  'k': 33,
  'E': 34,
  'L': 35,
  'P': 36,
  'F': 37,
  'w': 38,
  'p': 39,
  'N': 40,
  'K': 41,
  'V': 42,
  'O': 43,
  'I': 44,
  'z': 45,
  'Z': 46,
  'x': 47,
  'U': 48,
  'Q': 49,
  'j': 50,
  '-': 51,
  'Y': 52,
  'X': 53,
  'q': 54})

In [128]:
from keras.models import Sequential
from keras.layers import LSTM,Bidirectional,Dense,Embedding

In [129]:
def createModel(vocabSize,seqLength):
    model = Sequential([
        Embedding(vocabSize,seqLength,input_length=seqLength),
        Bidirectional(LSTM(250,return_sequences=True)),
        Bidirectional(LSTM(200,return_sequences=True)),
        LSTM(150),
        Dense(100,activation='relu'),
        Dense(50,activation='relu'),
        Dense(vocabSize,activation='softmax')
    ])
    model.compile(
        loss='categorical_crossentropy',
        optimizer='adam',
        metrics=['accuracy']
    )
    model.summary()
    return model

In [130]:
model = createModel(vocabSize,seqLength)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 15, 15)            825       
                                                                 
 bidirectional_2 (Bidirectio  (None, 15, 500)          532000    
 nal)                                                            
                                                                 
 bidirectional_3 (Bidirectio  (None, 15, 400)          1121600   
 nal)                                                            
                                                                 
 lstm_5 (LSTM)               (None, 150)               330600    
                                                                 
 dense_3 (Dense)             (None, 100)               15100     
                                                                 
 dense_4 (Dense)             (None, 50)               

In [132]:
history = model.fit(
                    xFeatures,
                    yLabelsBinary,
                    batch_size=32,
                    epochs=50,
                    verbose=True
                   )

Epoch 1/50
451/451 [==============================] - 80s 178ms/step - loss: 2.6200 - accuracy: 0.2495
Epoch 2/50
451/451 [==============================] - 89s 198ms/step - loss: 2.4439 - accuracy: 0.2835
Epoch 3/50
451/451 [==============================] - 87s 192ms/step - loss: 2.4039 - accuracy: 0.2879
Epoch 4/50
451/451 [==============================] - 79s 175ms/step - loss: 2.3238 - accuracy: 0.3092
Epoch 5/50
451/451 [==============================] - 78s 172ms/step - loss: 2.2735 - accuracy: 0.3155
Epoch 6/50
451/451 [==============================] - 75s 167ms/step - loss: 2.2393 - accuracy: 0.3215
Epoch 7/50
451/451 [==============================] - 81s 179ms/step - loss: 2.2052 - accuracy: 0.3311
Epoch 8/50
451/451 [==============================] - 83s 184ms/step - loss: 2.1684 - accuracy: 0.3425
Epoch 9/50
451/451 [==============================] - 87s 192ms/step - loss: 2.1365 - accuracy: 0.3470
Epoch 10/50
451/451 [==============================] - 86s 190ms/step - l

In [133]:
model.save('textGeneration.h5')
dump(tokenizer,open('my_simpleTokenizer','wb'))
dump(history,open('model_history','wb'))

INFO:tensorflow:Assets written to: ram://b0f363ff-a68b-4b78-bd69-5741a839875f/assets


INFO:tensorflow:Assets written to: ram://b0f363ff-a68b-4b78-bd69-5741a839875f/assets


In [149]:
def convertToText(model,seedText,tokenizer,N):
    for i in range(0,N):
        # converting the seedText to tokens
        newText = seedText
        wordIndex = tokenizer.word_index
        processed = np.array([wordIndex[word] for word in newText if word in wordIndex])
        processed = pad_sequences([processed],maxlen=15,padding='pre')
        # getting predictions
        prediction = model.predict(processed,verbose=False)[0]
        index = np.argmax(prediction)
#         wordIndex = yLabels[index]
        actualWord = tokenizer.index_word[index]
        seedText += actualWord
    return seedText

In [152]:
for i in convertToText(model,'',tokenizer,100):
    print(i,end='')

angelbert






o

o


o

o











e

o
t

o

o











e

o
t

o

o











e

o
t

o

o


In [ ]:
history.history.